[package]
name = "huff-comp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
huff-ast.workspace = true
alloy-primitives.workspace = true
revm-interpreter.workspace = true
