[package]
name = "huff-ast"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-dyn-abi.workspace = true
alloy-primitives.workspace = true
revm-interpreter.workspace = true
chumsky.workspace = true
