[package]
name = "huff-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
huff-ast.workspace = true
huff-comp.workspace = true

ariadne.workspace = true
clap.workspace = true

[[bin]]
name = "huff"
path = "src/main.rs"
