[package]
name = "ast"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-dyn-abi.workspace = true
alloy-primitives.workspace = true
ariadne.workspace = true
chumsky.workspace = true
evm-glue.workspace = true
